# Generated by Django 3.1.3 on 2020-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('choice1', models.CharField(max_length=100)),
                ('correct_choice', models.IntegerField()),
            ],
        ),
    ]
